### ISSUE TITLE
Library generator removes all comments on Cargo.toml

### ISSUE THREAD

**Issue by abbudao** [Cammisuli/monodon#35]
Hey @Cammisuli, how is it going?
I just found out that the generator for new libraries is removing all comments on `Cargo.toml`. This is a bit bothersome because I find it very useful when running a monorepo to explain some dependencies and group them, for instance:
```toml
[workspace.dependencies]
# log/tracing
tracing = "0.1"
tracing-subscriber = "0.3"

# datetime
chrono = { version = "0.4", features = ["serde"] }

# database
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres", "macros", "chrono" ] }

# testing
approx = "0.5"
ntest = "0.9"
axum-test= "13.1.1"
``` 
This has been extremely helpful for new Rust developers who still need to learn the ecosystem.

To reproduce, paste the above dependencies on root `Cargo.toml` with comments and run a generator:
 `yarn nx g @monodon/rust:lib my-lib` 

I need to dig more, but it's probably related to https://github.com/LongTengDao/j-toml/issues/19 ?
