### ISSUE TITLE
@monodon/rust "dependencyVersion" nullability in releaseVersionGenerator

### ISSUE THREAD

**Issue by LockedThread** [Cammisuli/monodon#49]
I just started a new project using this and I am running into an issue, I have made a workaround and will make a PR for it.

# Reproducible Setup

## `apps/api/Cargo.toml`
```toml
[package]
name = 'api'
version = '0.1.1-0'
edition = '2021'
publish = false

[dependencies]
customer_service = { path = '../../libs/grpc/customer_service' }
```

## `libs/grpc/customer_service/Cargo.toml`
```toml
[package]
name = "customer_service"
version = "0.1.1-0"
edition = "2021"
publish = false
```

## Description
When starting a project without the versions for dependencies being pinned in the dependent list this error occurs:

```log
customer_service 🔍 Reading data for crate "customer_service" from libs/grpc/customer_service/Cargo.toml
customer_service 📄 Resolved the current version as 0.1.1-0 from libs/grpc/customer_service/Cargo.toml
customer_service ✍️  New version 0.1.2-0 written to libs/grpc/customer_service/Cargo.toml
customer_service ✍️  Applying new version 0.1.2-0 to 1 package which depends on customer_service

 NX   Cannot read properties of undefined (reading 'match')

TypeError: Cannot read properties of undefined (reading 'match')
    at releaseVersionGenerator (/workspaces/unknot-new/node_modules/@monodon/rust/src/generators/release-version/release-version.js:254:67)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runVersionOnProjects (/workspaces/unknot-new/node_modules/nx/src/command-line/release/version.js:283:28)
    at async releaseVersion (/workspaces/unknot-new/node_modules/nx/src/command-line/release/version.js:182:39)
    at async release (/workspaces/unknot-new/node_modules/nx/src/command-line/release/release.js:50:27)
    at async handleErrors (/workspaces/unknot-new/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/workspaces/unknot-new/node_modules/nx/src/command-line/release/command-object.js:89:24)
```
The line in question is https://github.com/Cammisuli/monodon/blob/655ef24d63255e478251b0ffa3afb725b6ba3867/packages/rust/src/generators/release-version/release-version.ts#L431

When printing the `dependencyData` variable I get the following:
```log
dependencyData= Object <[Object: null prototype] {}> {
  path: '../../libs/grpc/customer_service'
}
```

This is caused because the version is not yet pinned. The simplest solution, and the solution that has been working for me so far, has been to just simply add a null check. I do not see anything wrong with doing this please let me know if you see something I do not.
